package ke.co.banit.flowmart.presentation.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF865300)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFB046)
val onPrimaryContainerLight = Color(0xFF492B00)
val secondaryLight = Color(0xFF003DAF)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF005CFF)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF5A6400)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBBCB33)
val onTertiaryContainerLight = Color(0xFF303600)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF221A11)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF221A11)
val surfaceVariantLight = Color(0xFFF6DFC7)
val onSurfaceVariantLight = Color(0xFF534433)
val outlineLight = Color(0xFF867461)
val outlineVariantLight = Color(0xFFD9C3AC)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382F25)
val inverseOnSurfaceLight = Color(0xFFFFEEDF)
val inversePrimaryLight = Color(0xFFFFB960)
val surfaceDimLight = Color(0xFFE7D7C9)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E6)
val surfaceContainerLight = Color(0xFFFCEBDC)
val surfaceContainerHighLight = Color(0xFFF6E5D6)
val surfaceContainerHighestLight = Color(0xFFF0E0D1)

val primaryLightMediumContrast = Color(0xFF603B00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFFA46700)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF0038A4)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF005CFF)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF404700)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF707B00)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF8F4)
val onBackgroundLightMediumContrast = Color(0xFF221A11)
val surfaceLightMediumContrast = Color(0xFFFFF8F4)
val onSurfaceLightMediumContrast = Color(0xFF221A11)
val surfaceVariantLightMediumContrast = Color(0xFFF6DFC7)
val onSurfaceVariantLightMediumContrast = Color(0xFF4F402F)
val outlineLightMediumContrast = Color(0xFF6D5C4A)
val outlineVariantLightMediumContrast = Color(0xFF8A7864)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF382F25)
val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEEDF)
val inversePrimaryLightMediumContrast = Color(0xFFFFB960)
val surfaceDimLightMediumContrast = Color(0xFFE7D7C9)
val surfaceBrightLightMediumContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1E6)
val surfaceContainerLightMediumContrast = Color(0xFFFCEBDC)
val surfaceContainerHighLightMediumContrast = Color(0xFFF6E5D6)
val surfaceContainerHighestLightMediumContrast = Color(0xFFF0E0D1)

val primaryLightHighContrast = Color(0xFF341D00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF603B00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF001C5C)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF0038A4)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF202500)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF404700)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF8F4)
val onBackgroundLightHighContrast = Color(0xFF221A11)
val surfaceLightHighContrast = Color(0xFFFFF8F4)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFF6DFC7)
val onSurfaceVariantLightHighContrast = Color(0xFF2E2213)
val outlineLightHighContrast = Color(0xFF4F402F)
val outlineVariantLightHighContrast = Color(0xFF4F402F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF382F25)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFFE8D2)
val surfaceDimLightHighContrast = Color(0xFFE7D7C9)
val surfaceBrightLightHighContrast = Color(0xFFFFF8F4)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFFFF1E6)
val surfaceContainerLightHighContrast = Color(0xFFFCEBDC)
val surfaceContainerHighLightHighContrast = Color(0xFFF6E5D6)
val surfaceContainerHighestLightHighContrast = Color(0xFFF0E0D1)

val primaryDark = Color(0xFFFFD3A2)
val onPrimaryDark = Color(0xFF472A00)
val primaryContainerDark = Color(0xFFF79D00)
val onPrimaryContainerDark = Color(0xFF392100)
val secondaryDark = Color(0xFFB5C4FF)
val onSecondaryDark = Color(0xFF00287B)
val secondaryContainerDark = Color(0xFF0054EB)
val onSecondaryContainerDark = Color(0xFFFFFFFF)
val tertiaryDark = Color(0xFFD4E54B)
val onTertiaryDark = Color(0xFF2E3300)
val tertiaryContainerDark = Color(0xFFAABA20)
val onTertiaryContainerDark = Color(0xFF242800)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF191209)
val onBackgroundDark = Color(0xFFF0E0D1)
val surfaceDark = Color(0xFF191209)
val onSurfaceDark = Color(0xFFF0E0D1)
val surfaceVariantDark = Color(0xFF534433)
val onSurfaceVariantDark = Color(0xFFD9C3AC)
val outlineDark = Color(0xFFA18D79)
val outlineVariantDark = Color(0xFF534433)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0E0D1)
val inverseOnSurfaceDark = Color(0xFF382F25)
val inversePrimaryDark = Color(0xFF865300)
val surfaceDimDark = Color(0xFF191209)
val surfaceBrightDark = Color(0xFF41372D)
val surfaceContainerLowestDark = Color(0xFF140D05)
val surfaceContainerLowDark = Color(0xFF221A11)
val surfaceContainerDark = Color(0xFF261E15)
val surfaceContainerHighDark = Color(0xFF31281F)
val surfaceContainerHighestDark = Color(0xFF3D3329)

val primaryDarkMediumContrast = Color(0xFFFFD3A2)
val onPrimaryDarkMediumContrast = Color(0xFF361F00)
val primaryContainerDarkMediumContrast = Color(0xFFF79D00)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFBBC9FF)
val onSecondaryDarkMediumContrast = Color(0xFF001242)
val secondaryContainerDarkMediumContrast = Color(0xFF648AFF)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFD4E54B)
val onTertiaryDarkMediumContrast = Color(0xFF222700)
val tertiaryContainerDarkMediumContrast = Color(0xFFAABA20)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF191209)
val onBackgroundDarkMediumContrast = Color(0xFFF0E0D1)
val surfaceDarkMediumContrast = Color(0xFF191209)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF7)
val surfaceVariantDarkMediumContrast = Color(0xFF534433)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDDC7B1)
val outlineDarkMediumContrast = Color(0xFFB49F8A)
val outlineVariantDarkMediumContrast = Color(0xFF93806C)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFF0E0D1)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF31281F)
val inversePrimaryDarkMediumContrast = Color(0xFF673F00)
val surfaceDimDarkMediumContrast = Color(0xFF191209)
val surfaceBrightDarkMediumContrast = Color(0xFF41372D)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF140D05)
val surfaceContainerLowDarkMediumContrast = Color(0xFF221A11)
val surfaceContainerDarkMediumContrast = Color(0xFF261E15)
val surfaceContainerHighDarkMediumContrast = Color(0xFF31281F)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3329)

val primaryDarkHighContrast = Color(0xFFFFFAF7)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFFFBE6F)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFCFAFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBBC9FF)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFAFFC8)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFC4D53C)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF191209)
val onBackgroundDarkHighContrast = Color(0xFFF0E0D1)
val surfaceDarkHighContrast = Color(0xFF191209)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF534433)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF7)
val outlineDarkHighContrast = Color(0xFFDDC7B1)
val outlineVariantDarkHighContrast = Color(0xFFDDC7B1)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFF0E0D1)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3E2400)
val surfaceDimDarkHighContrast = Color(0xFF191209)
val surfaceBrightDarkHighContrast = Color(0xFF41372D)
val surfaceContainerLowestDarkHighContrast = Color(0xFF140D05)
val surfaceContainerLowDarkHighContrast = Color(0xFF221A11)
val surfaceContainerDarkHighContrast = Color(0xFF261E15)
val surfaceContainerHighDarkHighContrast = Color(0xFF31281F)
val surfaceContainerHighestDarkHighContrast = Color(0xFF3D3329)        // Light Red


val lightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val darkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark
)
